# -- Defaults to the value configured in the "giantswarm" App Catalog.
baseDomain: ""

global:
  # -- SLA checks' defaults.
  checkDefaults:
    # -- Default base domain for the ingress, defaults to .baseDomain. Can be
    # overwritten in a specific check.
    baseDomain: ""
    blackboxExporter:
      # -- Namespace selector to select blackbox_exporter Pod(s) as defined in
      # `kubectl explain servicemonitor.spec.namespaceSelector`. Can be
      # overwritten in a specific check.
      namespaceSelector:
        matchNames:
          - kube-system
      # -- Selector to select blackbox_exporter Pod(s) as defined in `kubectl
      # explain servicemonitor.spec.selector`. Defaults to
      # .checkDefaults.blackboxExporter.selector. Can be overwritten in a
      # specific check.
      selector:
        matchLabels:
          app.kubernetes.io/instance: prometheus-blackbox-exporter
          app.kubernetes.io/name: prometheus-blackbox-exporter
    certManager:
      clusterIssuer:
        # -- Name of the ClusterIssuer to be used to generate TLS certificates
        # for the measured Ingress object. Defaults to
        # .checkDefaults.certManager.clusterIssuer.name
        name: letsencrypt-giantswarm

  # @schema
  # type: array
  # items:
  #   type: object
  #   properties:
  #     ingressClass:
  #       type: string
  #       description: |
  #         Ingress class, subject to SLA.
  #     baseDomain:
  #       required: false
  #       type: string
  #       description: |
  #         Base domain for the ingress, defaults to .checkDefaults.baseDomain.
  #     blackboxExporter:
  #       required: false
  #       type: object
  #       properties:
  #         namespaceSelector:
  #           type: object
  #           description: |
  #             Namespace selector to select blackbox_exporter Pod(s) as defined
  #             in `kubectl explain servicemonitor.spec.namespaceSelector`.
  #             Defaults to .checkDefaults.blackboxExporter.namespaceSelector.
  #         selector:
  #           type: object
  #           description: |
  #             Selector to select blackbox_exporter Pod(s) as defined in
  #             `kubectl explain servicemonitor.spec.selector`. Defaults to
  #             .checkDefaults.blackboxExporter.selector.
  #     certManager:
  #       required: false
  #       type: object
  #       properties:
  #         clusterIssuer:
  #           type: object
  #           properties:
  #             name:
  #               type: string
  #               description: |
  #                 Name of the ClusterIssuer to be used to generate TLS
  #                 certificates for the measured Ingress object. Defaults to
  #                 .checkDefaults.certManager.clusterIssuer.name
  # @schema
  # -- SLA checks for ingress classes.
  checks: []
  # - ingressClass: nginx      # required
  #   baseDomain: ""           # defaults .checkDefaults.baseDomain 
  #   certManager: 
  #     clusterIssuer:
  #       name:                # defaults to .checkDefaults.certManager
  #   blackboxExporter:
  #     namespaceSelector: {}  # defaults to checkDefaults.blackboxExporter.namespaceSelector
  #     selector: {}           # defaults to checkDefaults.blackboxExporter.selector
