apiVersion: v2
appVersion: 0.0.1
name: ingress-sla
description: Resources required to provide metrics to Giant Swarm SLA dashboard.
home: https://github.com/giantswarm/ingress-sla-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
version: 0.2.0
annotations:
  application.giantswarm.io/team: "cabbage"
