name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Check if schema is up to date
        run: make gen-schema && git diff --exit-code

      - name: Run chart unit tests
        run: make unit-test
